export const TAG_CATEGORIES = [
  {
    label: "Ernährungsform",
    options: [
      { value: "vegetarisch", label: "🥦 Vegetarisch", color: "#4CAF50" },
      { value: "vegan", label: "🌱 Vegan", color: "#2E7D32" },
      { value: "pescetarisch", label: "🐟 Pescetarisch", color: "#009688" },
      { value: "glutenfrei", label: "🚫 Glutenfrei", color: "#FF9800" },
      { value: "laktosefrei", label: "🥛 Laktosefrei", color: "#FFC107" },
      { value: "keto", label: "🥓 Keto", color: "#795548" },
      { value: "lowcarb", label: "🍗 Low-Carb", color: "#607D8B" },
      { value: "paleo", label: "🥩 Paleo", color: "#8D6E63" },
      { value: "zuckerfrei", label: "🍬 Zuckerfrei", color: "#E91E63" },
      { value: "histaminarm", label: "🧪 Histaminarm", color: "#9C27B0" },
      { value: "fodmap", label: "🍎 FODMAP-arm", color: "#673AB7" },
    ],
  },
  {
    label: "Küche / Region",
    options: [
      { value: "deutsch", label: "🇩🇪 Deutsch", color: "#2196F3" },
      { value: "italienisch", label: "🇮🇹 Italienisch", color: "#F44336" },
      { value: "franzoesisch", label: "🇫🇷 Französisch", color: "#3F51B5" },
      { value: "asiatisch", label: "🥢 Asiatisch", color: "#FF5722" },
      { value: "chinesisch", label: "🇨🇳 Chinesisch", color: "#D32F2F" },
      { value: "japanisch", label: "🇯🇵 Japanisch", color: "#C2185B" },
      { value: "thailendisch", label: "🇹🇭 Thailändisch", color: "#7B1FA2" },
      { value: "indisch", label: "🇮🇳 Indisch", color: "#FF9800" },
      { value: "mexikanisch", label: "🇲🇽 Mexikanisch", color: "#512DA8" },
      { value: "griechisch", label: "🇬🇷 Griechisch", color: "#009688" },
      { value: "spanisch", label: "🇪🇸 Spanisch", color: "#FF5722" },
      { value: "amerikanisch", label: "🇺🇸 Amerikanisch", color: "#1976D2" },
      { value: "orientalisch", label: "🕌 Orientalisch", color: "#00BCD4" },
      { value: "skandinavisch", label: "🇸🇪 Skandinavisch", color: "#009688" },
      { value: "fusion", label: "🔀 Fusion", color: "#673AB7" },
    ],
  },
  {
    label: "Mahlzeit / Anlass",
    options: [
      { value: "fruehstueck", label: "🍳 Frühstück", color: "#FFC107" },
      { value: "brunch", label: "🥞 Brunch", color: "#FF9800" },
      { value: "mittagessen", label: "🍲 Mittagessen", color: "#4CAF50" },
      { value: "abendessen", label: "🍛 Abendessen", color: "#2E7D32" },
      { value: "snack", label: "🍪 Snack", color: "#795548" },
      { value: "vorspeise", label: "🍴 Vorspeise", color: "#607D8B" },
      { value: "hauptgericht", label: "🍗 Hauptgericht", color: "#F44336" },
      { value: "beilage", label: "🥔 Beilage", color: "#FF5722" },
      { value: "dessert", label: "🍰 Dessert", color: "#E91E63" },
      { value: "backen", label: "🍞 Backen", color: "#9C27B0" },
      { value: "grillen", label: "🔥 Grillen", color: "#D32F2F" },
      { value: "party", label: "🎉 Party", color: "#FF4081" },
      { value: "mealprep", label: "📦 Meal Prep", color: "#00BCD4" },
      {
        value: "resteverwertung",
        label: "♻️ Resteverwertung",
        color: "#4CAF50",
      },
      { value: "festlich", label: "🎄 Festlich", color: "#C2185B" },
    ],
  },
  {
    label: "Zeitaufwand",
    options: [
      { value: "schnell", label: "⏱️ Schnell (<30 Min)", color: "#4CAF50" },
      { value: "mittel", label: "⏳ Mittel (30-60 Min)", color: "#FF9800" },
      { value: "langsam", label: "🐢 Langsam (>60 Min)", color: "#F44336" },
      { value: "uber_nacht", label: "🌙 Über Nacht", color: "#3F51B5" },
    ],
  },
  {
    label: "Schärfe / Geschmack",
    options: [
      { value: "mild", label: "😊 Mild", color: "#4CAF50" },
      { value: "mittelscharf", label: "🌶️ Mittelscharf", color: "#FF9800" },
      { value: "scharf", label: "🔥 Scharf", color: "#F44336" },
      { value: "suess", label: "🍭 Süß", color: "#E91E63" },
      { value: "sauer", label: "🍋 Sauer", color: "#CDDC39" },
      { value: "herzhaft", label: "🧀 Herzhaft", color: "#795548" },
      { value: "umami", label: "🍄 Umami", color: "#607D8B" },
    ],
  },
  {
    label: "Schwierigkeit",
    options: [
      { value: "einfach", label: "👶 Einfach", color: "#4CAF50" },
      { value: "mittel", label: "👩‍🍳 Mittel", color: "#FF9800" },
      { value: "anspruchsvoll", label: "🧑‍🍳 Anspruchsvoll", color: "#F44336" },
    ],
  },
  {
    label: "Trends / Sonderkategorien",
    options: [
      { value: "superfood", label: "💪 Superfood", color: "#2E7D32" },
      { value: "comfort_food", label: "🍕 Comfort Food", color: "#FF5722" },
      { value: "street_food", label: "🌭 Street Food", color: "#7B1FA2" },
      { value: "fast_food", label: "🍔 Fast Food", color: "#D32F2F" },
      { value: "healthy", label: "💚 Healthy", color: "#4CAF50" },
      { value: "traditionell", label: "👵 Traditionell", color: "#795548" },
      { value: "modern", label: "🆕 Modern", color: "#00BCD4" },
      { value: "nachhaltig", label: "♻️ Nachhaltig", color: "#2E7D32" },
      {
        value: "saisonale_zutaten",
        label: "🍂 Saisonale Zutaten",
        color: "#FF9800",
      },
    ],
  },
];
